### ISSUE TITLE
Version 6.0 : Breaking Changes 

### ISSUE THREAD

**Issue by TanvirArjel** [TanvirArjel/EFCore.GenericRepository#25]
Currently, `IRepository` command methods are calling `await _dbContext.SaveChangesAsync()` internally, which arguably breaks the single responsibility pattern. So we have decided to bring the `await _dbContext.SaveChangesAsync()` out of the following methods:

```C#
1. InsertAsync();
2. UpdateAsync();
3. DeleteAsync();
```

The above methods will be replaced with the following methods:
```C#
1. Add();
2. Update();
3. Remove();
```

And to persist the changes to the database, the user has to call the `await _repository.SaveChangesAsync()` explicitly.

Currently:
```C#
_repository.InsertAsync(employee);
```
**In from version 6.0:**

```C#
_repository.Add(employee);
await _repository.SaveChangesAsync();
```

However, what should be the next method names:

```C#
1. Add();
2. Update();
3. Remove();
```

or

```C#
1. Insert();
2. Update();
3. Delete();
```

Please share your thoughts.

**Comment by Krzysztofz01** [comment]
The `Add()`, `Update()`, `Remove()` approach seems fine. But i think that the `SaveChanges()` method should have a different name. EfCore `SaveChanges()` method works globally and is finalizing the transaction for all tracked entities. To make the ,,save'' method look more repository (which is representing a single entity) related, we can choose a different name, mayby `Commit()`?

**Comment by TanvirArjel** [comment]
Thank you for your opinion:

>EfCore SaveChanges() method works globally and is finalizing the transaction for all tracked entities. To make the ,,save'' method look more repository (which is representing a single entity) related, we can choose a different name, mayby Commit()?

However, Our `IRepository` methods are generic, so you can add multiple command operations for multiple entities one by one and `SaveCahnges` all at once. That's why we are naming it `SaveChangesAsync()`.

**Comment by serdarozkan41** [comment]
While sole responsibility is important, it is not a requirement.

Names
1. Add();
2. Update();
3. Delete();
instead of changing
1. InsertAsync(); with save
1. Add(); without saving
2. UpdateAsync(); with save
2. Update(); without saving
3. DeleteAsync(); with save
3. Delete(); without saving

Wouldn't it be much more reasonable to continue as ?

Or could this be an option?

`services.AddGenericRepository<YourDbContext>().AutoSave(true);`

I understand that principles are important.
but this is not a client project, is it really that important?
**Just asking :)**

**Comment by TanvirArjel** [comment]
@serdarozkan41 Thank you so much for your opinion. If we keep all the methods, it will create a lot of confusion for the end users. I would like to keep things simple.

**Comment by HybridSolutions** [comment]
I don't see any disadvantage on the new approach, as long as multiple operations can still work in case of using transactions. Don't like the .Commit() since EF Core uses this to commit transactions and it would be confusing. I think the closest it ressembles to EF Core the better, so Add(), Remove() and Update() are my choices.
